# Generated by Django 5.0.2 on 2024-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project_title',
        ),
    ]
