# Generated by Django 5.0.2 on 2024-03-03 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_project_project_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apidata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('api_data', models.CharField(max_length=255)),
                ('api_description', models.TextField()),
                ('project_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
